// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacex/api/device/common.proto

package device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BootReason int32

const (
	BootReason_BOOT_REASON_UNKNOWN BootReason = 0
	BootReason_FORGOTTEN           BootReason = 1
	BootReason_POWER_CYCLE         BootReason = 2
	BootReason_COMMAND             BootReason = 3
	BootReason_SOFTWARE_UPDATE     BootReason = 4
	BootReason_CONFIG_UPDATE       BootReason = 5
	BootReason_UPTIME_FDIR         BootReason = 6
	BootReason_REPEATER_FDIR       BootReason = 7
)

var BootReason_name = map[int32]string{
	0: "BOOT_REASON_UNKNOWN",
	1: "FORGOTTEN",
	2: "POWER_CYCLE",
	3: "COMMAND",
	4: "SOFTWARE_UPDATE",
	5: "CONFIG_UPDATE",
	6: "UPTIME_FDIR",
	7: "REPEATER_FDIR",
}

var BootReason_value = map[string]int32{
	"BOOT_REASON_UNKNOWN": 0,
	"FORGOTTEN":           1,
	"POWER_CYCLE":         2,
	"COMMAND":             3,
	"SOFTWARE_UPDATE":     4,
	"CONFIG_UPDATE":       5,
	"UPTIME_FDIR":         6,
	"REPEATER_FDIR":       7,
}

func (x BootReason) String() string {
	return proto.EnumName(BootReason_name, int32(x))
}

func (BootReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{0}
}

type EthernetNetworkInterface_Duplex int32

const (
	EthernetNetworkInterface_UNKNOWN EthernetNetworkInterface_Duplex = 0
	EthernetNetworkInterface_HALF    EthernetNetworkInterface_Duplex = 1
	EthernetNetworkInterface_FULL    EthernetNetworkInterface_Duplex = 2
)

var EthernetNetworkInterface_Duplex_name = map[int32]string{
	0: "UNKNOWN",
	1: "HALF",
	2: "FULL",
}

var EthernetNetworkInterface_Duplex_value = map[string]int32{
	"UNKNOWN": 0,
	"HALF":    1,
	"FULL":    2,
}

func (x EthernetNetworkInterface_Duplex) String() string {
	return proto.EnumName(EthernetNetworkInterface_Duplex_name, int32(x))
}

func (EthernetNetworkInterface_Duplex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{12, 0}
}

type DeviceInfo struct {
	Id                      string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardwareVersion         string    `protobuf:"bytes,2,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	SoftwareVersion         string    `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	ManufacturedVersion     string    `protobuf:"bytes,11,opt,name=manufactured_version,json=manufacturedVersion,proto3" json:"manufactured_version,omitempty"`
	CountryCode             string    `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	UtcOffsetS              int32     `protobuf:"varint,5,opt,name=utc_offset_s,json=utcOffsetS,proto3" json:"utc_offset_s,omitempty"`
	SoftwarePartitionsEqual bool      `protobuf:"varint,6,opt,name=software_partitions_equal,json=softwarePartitionsEqual,proto3" json:"software_partitions_equal,omitempty"`
	IsDev                   bool      `protobuf:"varint,7,opt,name=is_dev,json=isDev,proto3" json:"is_dev,omitempty"`
	Bootcount               int32     `protobuf:"varint,8,opt,name=bootcount,proto3" json:"bootcount,omitempty"`
	AntiRollbackVersion     int32     `protobuf:"varint,9,opt,name=anti_rollback_version,json=antiRollbackVersion,proto3" json:"anti_rollback_version,omitempty"`
	IsHitl                  bool      `protobuf:"varint,10,opt,name=is_hitl,json=isHitl,proto3" json:"is_hitl,omitempty"`
	Boot                    *BootInfo `protobuf:"bytes,1001,opt,name=boot,proto3" json:"boot,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}  `json:"-"`
	XXX_unrecognized        []byte    `json:"-"`
	XXX_sizecache           int32     `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{0}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeviceInfo) GetHardwareVersion() string {
	if m != nil {
		return m.HardwareVersion
	}
	return ""
}

func (m *DeviceInfo) GetSoftwareVersion() string {
	if m != nil {
		return m.SoftwareVersion
	}
	return ""
}

func (m *DeviceInfo) GetManufacturedVersion() string {
	if m != nil {
		return m.ManufacturedVersion
	}
	return ""
}

func (m *DeviceInfo) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *DeviceInfo) GetUtcOffsetS() int32 {
	if m != nil {
		return m.UtcOffsetS
	}
	return 0
}

func (m *DeviceInfo) GetSoftwarePartitionsEqual() bool {
	if m != nil {
		return m.SoftwarePartitionsEqual
	}
	return false
}

func (m *DeviceInfo) GetIsDev() bool {
	if m != nil {
		return m.IsDev
	}
	return false
}

func (m *DeviceInfo) GetBootcount() int32 {
	if m != nil {
		return m.Bootcount
	}
	return 0
}

func (m *DeviceInfo) GetAntiRollbackVersion() int32 {
	if m != nil {
		return m.AntiRollbackVersion
	}
	return 0
}

func (m *DeviceInfo) GetIsHitl() bool {
	if m != nil {
		return m.IsHitl
	}
	return false
}

func (m *DeviceInfo) GetBoot() *BootInfo {
	if m != nil {
		return m.Boot
	}
	return nil
}

type DeviceState struct {
	UptimeS              uint64   `protobuf:"varint,1,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceState) Reset()         { *m = DeviceState{} }
func (m *DeviceState) String() string { return proto.CompactTextString(m) }
func (*DeviceState) ProtoMessage()    {}
func (*DeviceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{1}
}

func (m *DeviceState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceState.Unmarshal(m, b)
}
func (m *DeviceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceState.Marshal(b, m, deterministic)
}
func (m *DeviceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceState.Merge(m, src)
}
func (m *DeviceState) XXX_Size() int {
	return xxx_messageInfo_DeviceState.Size(m)
}
func (m *DeviceState) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceState.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceState proto.InternalMessageInfo

func (m *DeviceState) GetUptimeS() uint64 {
	if m != nil {
		return m.UptimeS
	}
	return 0
}

type SignedData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedData) Reset()         { *m = SignedData{} }
func (m *SignedData) String() string { return proto.CompactTextString(m) }
func (*SignedData) ProtoMessage()    {}
func (*SignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{2}
}

func (m *SignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedData.Unmarshal(m, b)
}
func (m *SignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedData.Marshal(b, m, deterministic)
}
func (m *SignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedData.Merge(m, src)
}
func (m *SignedData) XXX_Size() int {
	return xxx_messageInfo_SignedData.Size(m)
}
func (m *SignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedData proto.InternalMessageInfo

func (m *SignedData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignedData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetNextIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextIdRequest) Reset()         { *m = GetNextIdRequest{} }
func (m *GetNextIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetNextIdRequest) ProtoMessage()    {}
func (*GetNextIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{3}
}

func (m *GetNextIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextIdRequest.Unmarshal(m, b)
}
func (m *GetNextIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextIdRequest.Marshal(b, m, deterministic)
}
func (m *GetNextIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextIdRequest.Merge(m, src)
}
func (m *GetNextIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetNextIdRequest.Size(m)
}
func (m *GetNextIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextIdRequest proto.InternalMessageInfo

type GetNextIdResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EpochId              uint64   `protobuf:"varint,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextIdResponse) Reset()         { *m = GetNextIdResponse{} }
func (m *GetNextIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextIdResponse) ProtoMessage()    {}
func (*GetNextIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{4}
}

func (m *GetNextIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextIdResponse.Unmarshal(m, b)
}
func (m *GetNextIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextIdResponse.Marshal(b, m, deterministic)
}
func (m *GetNextIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextIdResponse.Merge(m, src)
}
func (m *GetNextIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextIdResponse.Size(m)
}
func (m *GetNextIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextIdResponse proto.InternalMessageInfo

func (m *GetNextIdResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetNextIdResponse) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

type BootInfo struct {
	CountByReason        map[int32]int32 `protobuf:"bytes,1,rep,name=count_by_reason,json=countByReason,proto3" json:"count_by_reason,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	CountByReasonDelta   map[int32]int32 `protobuf:"bytes,4,rep,name=count_by_reason_delta,json=countByReasonDelta,proto3" json:"count_by_reason_delta,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	LastReason           BootReason      `protobuf:"varint,2,opt,name=last_reason,json=lastReason,proto3,enum=SpaceX.API.Device.BootReason" json:"last_reason,omitempty"`
	LastCount            int32           `protobuf:"varint,3,opt,name=last_count,json=lastCount,proto3" json:"last_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BootInfo) Reset()         { *m = BootInfo{} }
func (m *BootInfo) String() string { return proto.CompactTextString(m) }
func (*BootInfo) ProtoMessage()    {}
func (*BootInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{5}
}

func (m *BootInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootInfo.Unmarshal(m, b)
}
func (m *BootInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootInfo.Marshal(b, m, deterministic)
}
func (m *BootInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootInfo.Merge(m, src)
}
func (m *BootInfo) XXX_Size() int {
	return xxx_messageInfo_BootInfo.Size(m)
}
func (m *BootInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BootInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BootInfo proto.InternalMessageInfo

func (m *BootInfo) GetCountByReason() map[int32]int32 {
	if m != nil {
		return m.CountByReason
	}
	return nil
}

func (m *BootInfo) GetCountByReasonDelta() map[int32]int32 {
	if m != nil {
		return m.CountByReasonDelta
	}
	return nil
}

func (m *BootInfo) GetLastReason() BootReason {
	if m != nil {
		return m.LastReason
	}
	return BootReason_BOOT_REASON_UNKNOWN
}

func (m *BootInfo) GetLastCount() int32 {
	if m != nil {
		return m.LastCount
	}
	return 0
}

type PingTarget struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingTarget) Reset()         { *m = PingTarget{} }
func (m *PingTarget) String() string { return proto.CompactTextString(m) }
func (*PingTarget) ProtoMessage()    {}
func (*PingTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{6}
}

func (m *PingTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingTarget.Unmarshal(m, b)
}
func (m *PingTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingTarget.Marshal(b, m, deterministic)
}
func (m *PingTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingTarget.Merge(m, src)
}
func (m *PingTarget) XXX_Size() int {
	return xxx_messageInfo_PingTarget.Size(m)
}
func (m *PingTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_PingTarget.DiscardUnknown(m)
}

var xxx_messageInfo_PingTarget proto.InternalMessageInfo

func (m *PingTarget) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *PingTarget) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PingTarget) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PingResult struct {
	Target               *PingTarget `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	DropRate             float32     `protobuf:"fixed32,1,opt,name=dropRate,proto3" json:"dropRate,omitempty"`
	LatencyMs            float32     `protobuf:"fixed32,2,opt,name=latencyMs,proto3" json:"latencyMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PingResult) Reset()         { *m = PingResult{} }
func (m *PingResult) String() string { return proto.CompactTextString(m) }
func (*PingResult) ProtoMessage()    {}
func (*PingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{7}
}

func (m *PingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResult.Unmarshal(m, b)
}
func (m *PingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResult.Marshal(b, m, deterministic)
}
func (m *PingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResult.Merge(m, src)
}
func (m *PingResult) XXX_Size() int {
	return xxx_messageInfo_PingResult.Size(m)
}
func (m *PingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResult.DiscardUnknown(m)
}

var xxx_messageInfo_PingResult proto.InternalMessageInfo

func (m *PingResult) GetTarget() *PingTarget {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *PingResult) GetDropRate() float32 {
	if m != nil {
		return m.DropRate
	}
	return 0
}

func (m *PingResult) GetLatencyMs() float32 {
	if m != nil {
		return m.LatencyMs
	}
	return 0
}

type BondingChallenge struct {
	DishId               string   `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	WifiId               string   `protobuf:"bytes,2,opt,name=wifi_id,json=wifiId,proto3" json:"wifi_id,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BondingChallenge) Reset()         { *m = BondingChallenge{} }
func (m *BondingChallenge) String() string { return proto.CompactTextString(m) }
func (*BondingChallenge) ProtoMessage()    {}
func (*BondingChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{8}
}

func (m *BondingChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BondingChallenge.Unmarshal(m, b)
}
func (m *BondingChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BondingChallenge.Marshal(b, m, deterministic)
}
func (m *BondingChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BondingChallenge.Merge(m, src)
}
func (m *BondingChallenge) XXX_Size() int {
	return xxx_messageInfo_BondingChallenge.Size(m)
}
func (m *BondingChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_BondingChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_BondingChallenge proto.InternalMessageInfo

func (m *BondingChallenge) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

func (m *BondingChallenge) GetWifiId() string {
	if m != nil {
		return m.WifiId
	}
	return ""
}

func (m *BondingChallenge) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type AuthenticateRequest struct {
	Challenge            *SignedData `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{9}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetChallenge() *SignedData {
	if m != nil {
		return m.Challenge
	}
	return nil
}

type ChallengeResponse struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	CertificateChain     []byte   `protobuf:"bytes,2,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChallengeResponse) Reset()         { *m = ChallengeResponse{} }
func (m *ChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*ChallengeResponse) ProtoMessage()    {}
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{10}
}

func (m *ChallengeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChallengeResponse.Unmarshal(m, b)
}
func (m *ChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChallengeResponse.Marshal(b, m, deterministic)
}
func (m *ChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChallengeResponse.Merge(m, src)
}
func (m *ChallengeResponse) XXX_Size() int {
	return xxx_messageInfo_ChallengeResponse.Size(m)
}
func (m *ChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChallengeResponse proto.InternalMessageInfo

func (m *ChallengeResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ChallengeResponse) GetCertificateChain() []byte {
	if m != nil {
		return m.CertificateChain
	}
	return nil
}

type NetworkInterface struct {
	Name    string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Up      bool                      `protobuf:"varint,4,opt,name=up,proto3" json:"up,omitempty"`
	RxStats *NetworkInterface_RxStats `protobuf:"bytes,2,opt,name=rx_stats,json=rxStats,proto3" json:"rx_stats,omitempty"`
	TxStats *NetworkInterface_TxStats `protobuf:"bytes,3,opt,name=tx_stats,json=txStats,proto3" json:"tx_stats,omitempty"`
	// Types that are valid to be assigned to Interface:
	//	*NetworkInterface_Ethernet
	//	*NetworkInterface_Wifi
	Interface            isNetworkInterface_Interface `protobuf_oneof:"interface"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *NetworkInterface) Reset()         { *m = NetworkInterface{} }
func (m *NetworkInterface) String() string { return proto.CompactTextString(m) }
func (*NetworkInterface) ProtoMessage()    {}
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{11}
}

func (m *NetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterface.Unmarshal(m, b)
}
func (m *NetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterface.Marshal(b, m, deterministic)
}
func (m *NetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterface.Merge(m, src)
}
func (m *NetworkInterface) XXX_Size() int {
	return xxx_messageInfo_NetworkInterface.Size(m)
}
func (m *NetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterface proto.InternalMessageInfo

func (m *NetworkInterface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkInterface) GetUp() bool {
	if m != nil {
		return m.Up
	}
	return false
}

func (m *NetworkInterface) GetRxStats() *NetworkInterface_RxStats {
	if m != nil {
		return m.RxStats
	}
	return nil
}

func (m *NetworkInterface) GetTxStats() *NetworkInterface_TxStats {
	if m != nil {
		return m.TxStats
	}
	return nil
}

type isNetworkInterface_Interface interface {
	isNetworkInterface_Interface()
}

type NetworkInterface_Ethernet struct {
	Ethernet *EthernetNetworkInterface `protobuf:"bytes,1000,opt,name=ethernet,proto3,oneof"`
}

type NetworkInterface_Wifi struct {
	Wifi *WifiNetworkInterface `protobuf:"bytes,1001,opt,name=wifi,proto3,oneof"`
}

func (*NetworkInterface_Ethernet) isNetworkInterface_Interface() {}

func (*NetworkInterface_Wifi) isNetworkInterface_Interface() {}

func (m *NetworkInterface) GetInterface() isNetworkInterface_Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

func (m *NetworkInterface) GetEthernet() *EthernetNetworkInterface {
	if x, ok := m.GetInterface().(*NetworkInterface_Ethernet); ok {
		return x.Ethernet
	}
	return nil
}

func (m *NetworkInterface) GetWifi() *WifiNetworkInterface {
	if x, ok := m.GetInterface().(*NetworkInterface_Wifi); ok {
		return x.Wifi
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NetworkInterface) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NetworkInterface_Ethernet)(nil),
		(*NetworkInterface_Wifi)(nil),
	}
}

type NetworkInterface_RxStats struct {
	Bytes                uint64   `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Packets              uint64   `protobuf:"varint,2,opt,name=packets,proto3" json:"packets,omitempty"`
	FrameErrors          uint64   `protobuf:"varint,3,opt,name=frame_errors,json=frameErrors,proto3" json:"frame_errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInterface_RxStats) Reset()         { *m = NetworkInterface_RxStats{} }
func (m *NetworkInterface_RxStats) String() string { return proto.CompactTextString(m) }
func (*NetworkInterface_RxStats) ProtoMessage()    {}
func (*NetworkInterface_RxStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{11, 0}
}

func (m *NetworkInterface_RxStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterface_RxStats.Unmarshal(m, b)
}
func (m *NetworkInterface_RxStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterface_RxStats.Marshal(b, m, deterministic)
}
func (m *NetworkInterface_RxStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterface_RxStats.Merge(m, src)
}
func (m *NetworkInterface_RxStats) XXX_Size() int {
	return xxx_messageInfo_NetworkInterface_RxStats.Size(m)
}
func (m *NetworkInterface_RxStats) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterface_RxStats.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterface_RxStats proto.InternalMessageInfo

func (m *NetworkInterface_RxStats) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *NetworkInterface_RxStats) GetPackets() uint64 {
	if m != nil {
		return m.Packets
	}
	return 0
}

func (m *NetworkInterface_RxStats) GetFrameErrors() uint64 {
	if m != nil {
		return m.FrameErrors
	}
	return 0
}

type NetworkInterface_TxStats struct {
	Bytes                uint64   `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Packets              uint64   `protobuf:"varint,2,opt,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInterface_TxStats) Reset()         { *m = NetworkInterface_TxStats{} }
func (m *NetworkInterface_TxStats) String() string { return proto.CompactTextString(m) }
func (*NetworkInterface_TxStats) ProtoMessage()    {}
func (*NetworkInterface_TxStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{11, 1}
}

func (m *NetworkInterface_TxStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterface_TxStats.Unmarshal(m, b)
}
func (m *NetworkInterface_TxStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterface_TxStats.Marshal(b, m, deterministic)
}
func (m *NetworkInterface_TxStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterface_TxStats.Merge(m, src)
}
func (m *NetworkInterface_TxStats) XXX_Size() int {
	return xxx_messageInfo_NetworkInterface_TxStats.Size(m)
}
func (m *NetworkInterface_TxStats) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterface_TxStats.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterface_TxStats proto.InternalMessageInfo

func (m *NetworkInterface_TxStats) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *NetworkInterface_TxStats) GetPackets() uint64 {
	if m != nil {
		return m.Packets
	}
	return 0
}

type EthernetNetworkInterface struct {
	LinkDetected         bool                            `protobuf:"varint,1,opt,name=link_detected,json=linkDetected,proto3" json:"link_detected,omitempty"`
	SpeedMbps            uint32                          `protobuf:"varint,2,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	AutonegotiationOn    bool                            `protobuf:"varint,3,opt,name=autonegotiation_on,json=autonegotiationOn,proto3" json:"autonegotiation_on,omitempty"`
	Duplex               EthernetNetworkInterface_Duplex `protobuf:"varint,4,opt,name=duplex,proto3,enum=SpaceX.API.Device.EthernetNetworkInterface_Duplex" json:"duplex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *EthernetNetworkInterface) Reset()         { *m = EthernetNetworkInterface{} }
func (m *EthernetNetworkInterface) String() string { return proto.CompactTextString(m) }
func (*EthernetNetworkInterface) ProtoMessage()    {}
func (*EthernetNetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{12}
}

func (m *EthernetNetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthernetNetworkInterface.Unmarshal(m, b)
}
func (m *EthernetNetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthernetNetworkInterface.Marshal(b, m, deterministic)
}
func (m *EthernetNetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthernetNetworkInterface.Merge(m, src)
}
func (m *EthernetNetworkInterface) XXX_Size() int {
	return xxx_messageInfo_EthernetNetworkInterface.Size(m)
}
func (m *EthernetNetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_EthernetNetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_EthernetNetworkInterface proto.InternalMessageInfo

func (m *EthernetNetworkInterface) GetLinkDetected() bool {
	if m != nil {
		return m.LinkDetected
	}
	return false
}

func (m *EthernetNetworkInterface) GetSpeedMbps() uint32 {
	if m != nil {
		return m.SpeedMbps
	}
	return 0
}

func (m *EthernetNetworkInterface) GetAutonegotiationOn() bool {
	if m != nil {
		return m.AutonegotiationOn
	}
	return false
}

func (m *EthernetNetworkInterface) GetDuplex() EthernetNetworkInterface_Duplex {
	if m != nil {
		return m.Duplex
	}
	return EthernetNetworkInterface_UNKNOWN
}

type WifiNetworkInterface struct {
	ThermalStatus        *WifiNetworkInterface_ThermalStatus       `protobuf:"bytes,1,opt,name=thermal_status,json=thermalStatus,proto3" json:"thermal_status,omitempty"`
	InvalidPacketCounts  *WifiNetworkInterface_InvalidPacketCounts `protobuf:"bytes,2,opt,name=invalid_packet_counts,json=invalidPacketCounts,proto3" json:"invalid_packet_counts,omitempty"`
	Channel              uint32                                    `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	MissedBeacons        uint32                                    `protobuf:"varint,8,opt,name=missed_beacons,json=missedBeacons,proto3" json:"missed_beacons,omitempty"`
	LinkQuality          float64                                   `protobuf:"fixed64,4,opt,name=link_quality,json=linkQuality,proto3" json:"link_quality,omitempty"`
	SignalLevel          float64                                   `protobuf:"fixed64,5,opt,name=signal_level,json=signalLevel,proto3" json:"signal_level,omitempty"`
	NoiseLevel           float64                                   `protobuf:"fixed64,6,opt,name=noise_level,json=noiseLevel,proto3" json:"noise_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *WifiNetworkInterface) Reset()         { *m = WifiNetworkInterface{} }
func (m *WifiNetworkInterface) String() string { return proto.CompactTextString(m) }
func (*WifiNetworkInterface) ProtoMessage()    {}
func (*WifiNetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{13}
}

func (m *WifiNetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiNetworkInterface.Unmarshal(m, b)
}
func (m *WifiNetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiNetworkInterface.Marshal(b, m, deterministic)
}
func (m *WifiNetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiNetworkInterface.Merge(m, src)
}
func (m *WifiNetworkInterface) XXX_Size() int {
	return xxx_messageInfo_WifiNetworkInterface.Size(m)
}
func (m *WifiNetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiNetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_WifiNetworkInterface proto.InternalMessageInfo

func (m *WifiNetworkInterface) GetThermalStatus() *WifiNetworkInterface_ThermalStatus {
	if m != nil {
		return m.ThermalStatus
	}
	return nil
}

func (m *WifiNetworkInterface) GetInvalidPacketCounts() *WifiNetworkInterface_InvalidPacketCounts {
	if m != nil {
		return m.InvalidPacketCounts
	}
	return nil
}

func (m *WifiNetworkInterface) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *WifiNetworkInterface) GetMissedBeacons() uint32 {
	if m != nil {
		return m.MissedBeacons
	}
	return 0
}

func (m *WifiNetworkInterface) GetLinkQuality() float64 {
	if m != nil {
		return m.LinkQuality
	}
	return 0
}

func (m *WifiNetworkInterface) GetSignalLevel() float64 {
	if m != nil {
		return m.SignalLevel
	}
	return 0
}

func (m *WifiNetworkInterface) GetNoiseLevel() float64 {
	if m != nil {
		return m.NoiseLevel
	}
	return 0
}

type WifiNetworkInterface_ThermalStatus struct {
	Level                uint32   `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Temp                 uint32   `protobuf:"varint,2,opt,name=temp,proto3" json:"temp,omitempty"` // Deprecated: Do not use.
	Temp2                float64  `protobuf:"fixed64,3,opt,name=temp2,proto3" json:"temp2,omitempty"`
	PowerReduction       uint32   `protobuf:"varint,4,opt,name=power_reduction,json=powerReduction,proto3" json:"power_reduction,omitempty"`
	DutyCycle            uint32   `protobuf:"varint,5,opt,name=duty_cycle,json=dutyCycle,proto3" json:"duty_cycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiNetworkInterface_ThermalStatus) Reset()         { *m = WifiNetworkInterface_ThermalStatus{} }
func (m *WifiNetworkInterface_ThermalStatus) String() string { return proto.CompactTextString(m) }
func (*WifiNetworkInterface_ThermalStatus) ProtoMessage()    {}
func (*WifiNetworkInterface_ThermalStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{13, 0}
}

func (m *WifiNetworkInterface_ThermalStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiNetworkInterface_ThermalStatus.Unmarshal(m, b)
}
func (m *WifiNetworkInterface_ThermalStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiNetworkInterface_ThermalStatus.Marshal(b, m, deterministic)
}
func (m *WifiNetworkInterface_ThermalStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiNetworkInterface_ThermalStatus.Merge(m, src)
}
func (m *WifiNetworkInterface_ThermalStatus) XXX_Size() int {
	return xxx_messageInfo_WifiNetworkInterface_ThermalStatus.Size(m)
}
func (m *WifiNetworkInterface_ThermalStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiNetworkInterface_ThermalStatus.DiscardUnknown(m)
}

var xxx_messageInfo_WifiNetworkInterface_ThermalStatus proto.InternalMessageInfo

func (m *WifiNetworkInterface_ThermalStatus) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

// Deprecated: Do not use.
func (m *WifiNetworkInterface_ThermalStatus) GetTemp() uint32 {
	if m != nil {
		return m.Temp
	}
	return 0
}

func (m *WifiNetworkInterface_ThermalStatus) GetTemp2() float64 {
	if m != nil {
		return m.Temp2
	}
	return 0
}

func (m *WifiNetworkInterface_ThermalStatus) GetPowerReduction() uint32 {
	if m != nil {
		return m.PowerReduction
	}
	return 0
}

func (m *WifiNetworkInterface_ThermalStatus) GetDutyCycle() uint32 {
	if m != nil {
		return m.DutyCycle
	}
	return 0
}

type WifiNetworkInterface_InvalidPacketCounts struct {
	RxInvalidNwid        uint32   `protobuf:"varint,1,opt,name=rx_invalid_nwid,json=rxInvalidNwid,proto3" json:"rx_invalid_nwid,omitempty"`
	RxInvalidCrypt       uint32   `protobuf:"varint,2,opt,name=rx_invalid_crypt,json=rxInvalidCrypt,proto3" json:"rx_invalid_crypt,omitempty"`
	RxInvalidFrag        uint32   `protobuf:"varint,3,opt,name=rx_invalid_frag,json=rxInvalidFrag,proto3" json:"rx_invalid_frag,omitempty"`
	TxExcessiveRetries   uint32   `protobuf:"varint,4,opt,name=tx_excessive_retries,json=txExcessiveRetries,proto3" json:"tx_excessive_retries,omitempty"`
	InvalidMisc          uint32   `protobuf:"varint,5,opt,name=invalid_misc,json=invalidMisc,proto3" json:"invalid_misc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiNetworkInterface_InvalidPacketCounts) Reset() {
	*m = WifiNetworkInterface_InvalidPacketCounts{}
}
func (m *WifiNetworkInterface_InvalidPacketCounts) String() string { return proto.CompactTextString(m) }
func (*WifiNetworkInterface_InvalidPacketCounts) ProtoMessage()    {}
func (*WifiNetworkInterface_InvalidPacketCounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{13, 1}
}

func (m *WifiNetworkInterface_InvalidPacketCounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiNetworkInterface_InvalidPacketCounts.Unmarshal(m, b)
}
func (m *WifiNetworkInterface_InvalidPacketCounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiNetworkInterface_InvalidPacketCounts.Marshal(b, m, deterministic)
}
func (m *WifiNetworkInterface_InvalidPacketCounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiNetworkInterface_InvalidPacketCounts.Merge(m, src)
}
func (m *WifiNetworkInterface_InvalidPacketCounts) XXX_Size() int {
	return xxx_messageInfo_WifiNetworkInterface_InvalidPacketCounts.Size(m)
}
func (m *WifiNetworkInterface_InvalidPacketCounts) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiNetworkInterface_InvalidPacketCounts.DiscardUnknown(m)
}

var xxx_messageInfo_WifiNetworkInterface_InvalidPacketCounts proto.InternalMessageInfo

func (m *WifiNetworkInterface_InvalidPacketCounts) GetRxInvalidNwid() uint32 {
	if m != nil {
		return m.RxInvalidNwid
	}
	return 0
}

func (m *WifiNetworkInterface_InvalidPacketCounts) GetRxInvalidCrypt() uint32 {
	if m != nil {
		return m.RxInvalidCrypt
	}
	return 0
}

func (m *WifiNetworkInterface_InvalidPacketCounts) GetRxInvalidFrag() uint32 {
	if m != nil {
		return m.RxInvalidFrag
	}
	return 0
}

func (m *WifiNetworkInterface_InvalidPacketCounts) GetTxExcessiveRetries() uint32 {
	if m != nil {
		return m.TxExcessiveRetries
	}
	return 0
}

func (m *WifiNetworkInterface_InvalidPacketCounts) GetInvalidMisc() uint32 {
	if m != nil {
		return m.InvalidMisc
	}
	return 0
}

type LLAPosition struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt                  float64  `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LLAPosition) Reset()         { *m = LLAPosition{} }
func (m *LLAPosition) String() string { return proto.CompactTextString(m) }
func (*LLAPosition) ProtoMessage()    {}
func (*LLAPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{14}
}

func (m *LLAPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LLAPosition.Unmarshal(m, b)
}
func (m *LLAPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LLAPosition.Marshal(b, m, deterministic)
}
func (m *LLAPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LLAPosition.Merge(m, src)
}
func (m *LLAPosition) XXX_Size() int {
	return xxx_messageInfo_LLAPosition.Size(m)
}
func (m *LLAPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_LLAPosition.DiscardUnknown(m)
}

var xxx_messageInfo_LLAPosition proto.InternalMessageInfo

func (m *LLAPosition) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LLAPosition) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *LLAPosition) GetAlt() float64 {
	if m != nil {
		return m.Alt
	}
	return 0
}

type ECEFPosition struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ECEFPosition) Reset()         { *m = ECEFPosition{} }
func (m *ECEFPosition) String() string { return proto.CompactTextString(m) }
func (*ECEFPosition) ProtoMessage()    {}
func (*ECEFPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{15}
}

func (m *ECEFPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECEFPosition.Unmarshal(m, b)
}
func (m *ECEFPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECEFPosition.Marshal(b, m, deterministic)
}
func (m *ECEFPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECEFPosition.Merge(m, src)
}
func (m *ECEFPosition) XXX_Size() int {
	return xxx_messageInfo_ECEFPosition.Size(m)
}
func (m *ECEFPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_ECEFPosition.DiscardUnknown(m)
}

var xxx_messageInfo_ECEFPosition proto.InternalMessageInfo

func (m *ECEFPosition) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ECEFPosition) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ECEFPosition) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type InitiateRemoteSshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiateRemoteSshRequest) Reset()         { *m = InitiateRemoteSshRequest{} }
func (m *InitiateRemoteSshRequest) String() string { return proto.CompactTextString(m) }
func (*InitiateRemoteSshRequest) ProtoMessage()    {}
func (*InitiateRemoteSshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{16}
}

func (m *InitiateRemoteSshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiateRemoteSshRequest.Unmarshal(m, b)
}
func (m *InitiateRemoteSshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiateRemoteSshRequest.Marshal(b, m, deterministic)
}
func (m *InitiateRemoteSshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiateRemoteSshRequest.Merge(m, src)
}
func (m *InitiateRemoteSshRequest) XXX_Size() int {
	return xxx_messageInfo_InitiateRemoteSshRequest.Size(m)
}
func (m *InitiateRemoteSshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiateRemoteSshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitiateRemoteSshRequest proto.InternalMessageInfo

type InitiateRemoteSshResponse struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Stsafe               []byte   `protobuf:"bytes,3,opt,name=stsafe,proto3" json:"stsafe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiateRemoteSshResponse) Reset()         { *m = InitiateRemoteSshResponse{} }
func (m *InitiateRemoteSshResponse) String() string { return proto.CompactTextString(m) }
func (*InitiateRemoteSshResponse) ProtoMessage()    {}
func (*InitiateRemoteSshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac416429f8ffae6, []int{17}
}

func (m *InitiateRemoteSshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiateRemoteSshResponse.Unmarshal(m, b)
}
func (m *InitiateRemoteSshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiateRemoteSshResponse.Marshal(b, m, deterministic)
}
func (m *InitiateRemoteSshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiateRemoteSshResponse.Merge(m, src)
}
func (m *InitiateRemoteSshResponse) XXX_Size() int {
	return xxx_messageInfo_InitiateRemoteSshResponse.Size(m)
}
func (m *InitiateRemoteSshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiateRemoteSshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitiateRemoteSshResponse proto.InternalMessageInfo

func (m *InitiateRemoteSshResponse) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InitiateRemoteSshResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InitiateRemoteSshResponse) GetStsafe() []byte {
	if m != nil {
		return m.Stsafe
	}
	return nil
}

func init() {
	proto.RegisterEnum("SpaceX.API.Device.BootReason", BootReason_name, BootReason_value)
	proto.RegisterEnum("SpaceX.API.Device.EthernetNetworkInterface_Duplex", EthernetNetworkInterface_Duplex_name, EthernetNetworkInterface_Duplex_value)
	proto.RegisterType((*DeviceInfo)(nil), "SpaceX.API.Device.DeviceInfo")
	proto.RegisterType((*DeviceState)(nil), "SpaceX.API.Device.DeviceState")
	proto.RegisterType((*SignedData)(nil), "SpaceX.API.Device.SignedData")
	proto.RegisterType((*GetNextIdRequest)(nil), "SpaceX.API.Device.GetNextIdRequest")
	proto.RegisterType((*GetNextIdResponse)(nil), "SpaceX.API.Device.GetNextIdResponse")
	proto.RegisterType((*BootInfo)(nil), "SpaceX.API.Device.BootInfo")
	proto.RegisterMapType((map[int32]int32)(nil), "SpaceX.API.Device.BootInfo.CountByReasonDeltaEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "SpaceX.API.Device.BootInfo.CountByReasonEntry")
	proto.RegisterType((*PingTarget)(nil), "SpaceX.API.Device.PingTarget")
	proto.RegisterType((*PingResult)(nil), "SpaceX.API.Device.PingResult")
	proto.RegisterType((*BondingChallenge)(nil), "SpaceX.API.Device.BondingChallenge")
	proto.RegisterType((*AuthenticateRequest)(nil), "SpaceX.API.Device.AuthenticateRequest")
	proto.RegisterType((*ChallengeResponse)(nil), "SpaceX.API.Device.ChallengeResponse")
	proto.RegisterType((*NetworkInterface)(nil), "SpaceX.API.Device.NetworkInterface")
	proto.RegisterType((*NetworkInterface_RxStats)(nil), "SpaceX.API.Device.NetworkInterface.RxStats")
	proto.RegisterType((*NetworkInterface_TxStats)(nil), "SpaceX.API.Device.NetworkInterface.TxStats")
	proto.RegisterType((*EthernetNetworkInterface)(nil), "SpaceX.API.Device.EthernetNetworkInterface")
	proto.RegisterType((*WifiNetworkInterface)(nil), "SpaceX.API.Device.WifiNetworkInterface")
	proto.RegisterType((*WifiNetworkInterface_ThermalStatus)(nil), "SpaceX.API.Device.WifiNetworkInterface.ThermalStatus")
	proto.RegisterType((*WifiNetworkInterface_InvalidPacketCounts)(nil), "SpaceX.API.Device.WifiNetworkInterface.InvalidPacketCounts")
	proto.RegisterType((*LLAPosition)(nil), "SpaceX.API.Device.LLAPosition")
	proto.RegisterType((*ECEFPosition)(nil), "SpaceX.API.Device.ECEFPosition")
	proto.RegisterType((*InitiateRemoteSshRequest)(nil), "SpaceX.API.Device.InitiateRemoteSshRequest")
	proto.RegisterType((*InitiateRemoteSshResponse)(nil), "SpaceX.API.Device.InitiateRemoteSshResponse")
}

func init() { proto.RegisterFile("spacex/api/device/common.proto", fileDescriptor_8ac416429f8ffae6) }

var fileDescriptor_8ac416429f8ffae6 = []byte{
	// 1707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x5f, 0x6f, 0x23, 0xb7,
	0x11, 0xcf, 0x4a, 0xb2, 0xfe, 0xcc, 0x5a, 0xb6, 0x4c, 0x9f, 0x63, 0x9d, 0xdb, 0xb4, 0xee, 0x16,
	0x6d, 0x9c, 0x06, 0x55, 0x52, 0x07, 0x01, 0xd2, 0x04, 0x38, 0x54, 0x96, 0x56, 0x77, 0xba, 0xda,
	0x92, 0x4a, 0xe9, 0x72, 0x6d, 0x70, 0xe8, 0x82, 0xde, 0xa5, 0x24, 0xc2, 0xab, 0xe5, 0x66, 0xc9,
	0xb5, 0xa5, 0x00, 0x7d, 0xeb, 0x87, 0x28, 0x50, 0xa0, 0x1f, 0xa2, 0x1f, 0xa7, 0xcf, 0x7d, 0x68,
	0xbf, 0x41, 0x1f, 0x0b, 0x92, 0xbb, 0x92, 0xce, 0xe7, 0x2b, 0x2e, 0x7d, 0x12, 0xe7, 0x37, 0x33,
	0x3f, 0xce, 0x70, 0x86, 0xb3, 0x14, 0xfc, 0x48, 0xc4, 0xc4, 0xa7, 0xcb, 0x4f, 0x48, 0xcc, 0x3e,
	0x09, 0xe8, 0x2d, 0xf3, 0xe9, 0x27, 0x3e, 0x5f, 0x2c, 0x78, 0xd4, 0x8a, 0x13, 0x2e, 0x39, 0x3a,
	0x18, 0x2b, 0xfd, 0xef, 0x5b, 0xed, 0x51, 0xbf, 0xd5, 0xd5, 0x7a, 0xe7, 0x1f, 0x45, 0x00, 0xb3,
	0xec, 0x47, 0x53, 0x8e, 0xf6, 0xa0, 0xc0, 0x82, 0xa6, 0x75, 0x6a, 0x9d, 0xd5, 0x70, 0x81, 0x05,
	0xe8, 0x23, 0x68, 0xcc, 0x49, 0x12, 0xdc, 0x91, 0x84, 0x7a, 0xb7, 0x34, 0x11, 0x8c, 0x47, 0xcd,
	0x82, 0xd6, 0xee, 0xe7, 0xf8, 0xd7, 0x06, 0x56, 0xa6, 0x82, 0x4f, 0xe5, 0x6b, 0xa6, 0x45, 0x63,
	0x9a, 0xe3, 0xb9, 0xe9, 0xaf, 0xe0, 0xd1, 0x82, 0x44, 0xe9, 0x94, 0xf8, 0x32, 0x4d, 0x68, 0xb0,
	0x36, 0xb7, 0xb5, 0xf9, 0xe1, 0xb6, 0x2e, 0x77, 0xf9, 0x09, 0xec, 0xfa, 0x3c, 0x8d, 0x64, 0xb2,
	0xf2, 0x7c, 0x1e, 0xd0, 0x66, 0x49, 0x9b, 0xda, 0x19, 0xd6, 0xe1, 0x01, 0x45, 0xa7, 0xb0, 0x9b,
	0x4a, 0xdf, 0xe3, 0xd3, 0xa9, 0xa0, 0xd2, 0x13, 0xcd, 0x9d, 0x53, 0xeb, 0x6c, 0x07, 0x43, 0x2a,
	0xfd, 0xa1, 0x86, 0xc6, 0xe8, 0x4b, 0x78, 0xbc, 0x0e, 0x31, 0x26, 0x89, 0x64, 0x92, 0xf1, 0x48,
	0x78, 0xf4, 0xdb, 0x94, 0x84, 0xcd, 0xf2, 0xa9, 0x75, 0x56, 0xc5, 0xc7, 0xb9, 0xc1, 0x68, 0xad,
	0x77, 0x95, 0x1a, 0x1d, 0x41, 0x99, 0x09, 0x2f, 0xa0, 0xb7, 0xcd, 0x8a, 0x36, 0xdc, 0x61, 0xa2,
	0x4b, 0x6f, 0xd1, 0x0f, 0xa1, 0x76, 0xcd, 0xb9, 0xd4, 0x71, 0x34, 0xab, 0x7a, 0xc7, 0x0d, 0x80,
	0xce, 0xe1, 0x88, 0x44, 0x92, 0x79, 0x09, 0x0f, 0xc3, 0x6b, 0xe2, 0xdf, 0xac, 0x33, 0xad, 0x69,
	0xcb, 0x43, 0xa5, 0xc4, 0x99, 0x2e, 0xcf, 0xf4, 0x18, 0x2a, 0x4c, 0x78, 0x73, 0x26, 0xc3, 0x26,
	0xe8, 0x9d, 0xca, 0x4c, 0x3c, 0x63, 0x32, 0x44, 0x9f, 0x42, 0x49, 0x31, 0x37, 0xff, 0xad, 0x02,
	0xb0, 0xcf, 0x7f, 0xd0, 0x7a, 0xa3, 0x9a, 0xad, 0x0b, 0xce, 0xa5, 0xaa, 0x23, 0xd6, 0x96, 0xce,
	0x19, 0xd8, 0x46, 0x31, 0x96, 0x44, 0x52, 0xf4, 0x18, 0xaa, 0x69, 0x2c, 0xd9, 0x82, 0x7a, 0x42,
	0x97, 0xb8, 0x84, 0x2b, 0x46, 0x1e, 0x3b, 0x4f, 0x00, 0xc6, 0x6c, 0x16, 0xd1, 0xa0, 0x4b, 0x24,
	0x41, 0x08, 0x4a, 0x01, 0x91, 0x44, 0x1b, 0xed, 0x62, 0xbd, 0x56, 0x89, 0x0a, 0x36, 0x8b, 0x88,
	0xaa, 0x8a, 0x6e, 0x81, 0x5d, 0xbc, 0x01, 0x1c, 0x04, 0x8d, 0xa7, 0x54, 0x0e, 0xe8, 0x52, 0xf6,
	0x03, 0x4c, 0xbf, 0x4d, 0xa9, 0x90, 0xce, 0x13, 0x38, 0xd8, 0xc2, 0x44, 0xcc, 0x23, 0x41, 0xb7,
	0x1a, 0xac, 0xa4, 0x1b, 0xec, 0x31, 0x54, 0x69, 0xcc, 0xfd, 0xb9, 0xc7, 0x02, 0xcd, 0x5a, 0xc2,
	0x15, 0x2d, 0xf7, 0x03, 0xe7, 0xef, 0x45, 0xa8, 0xe6, 0x09, 0xa1, 0xaf, 0x61, 0x5f, 0x1f, 0xa9,
	0x77, 0xbd, 0xf2, 0x12, 0x4a, 0x04, 0x8f, 0x9a, 0xd6, 0x69, 0xf1, 0xcc, 0x3e, 0x6f, 0xfd, 0x8f,
	0x63, 0x68, 0x75, 0x94, 0xcb, 0xc5, 0x0a, 0x6b, 0x07, 0x57, 0x75, 0x0a, 0xae, 0xfb, 0xdb, 0x18,
	0x9a, 0xc2, 0xd1, 0x3d, 0x5e, 0x2f, 0xa0, 0xa1, 0x24, 0xcd, 0x92, 0x66, 0xff, 0xec, 0x9d, 0xd9,
	0xbb, 0xca, 0xcb, 0x6c, 0x81, 0xfc, 0x37, 0x14, 0xe8, 0x09, 0xd8, 0x21, 0x11, 0x32, 0x8f, 0x5d,
	0xa5, 0xba, 0x77, 0xfe, 0xc1, 0x5b, 0xd8, 0x8d, 0x23, 0x06, 0xe5, 0x91, 0xc5, 0xf9, 0x01, 0x68,
	0xc9, 0x33, 0x8d, 0x56, 0x34, 0x8d, 0xa6, 0x10, 0x1d, 0xc4, 0xc9, 0x6f, 0x00, 0xbd, 0x99, 0x2b,
	0x6a, 0x40, 0xf1, 0x86, 0xae, 0xf4, 0x69, 0xef, 0x60, 0xb5, 0x44, 0x8f, 0x60, 0xe7, 0x96, 0x84,
	0xa9, 0xa9, 0xe0, 0x0e, 0x36, 0xc2, 0x97, 0x85, 0x2f, 0xac, 0x13, 0x17, 0x8e, 0xdf, 0x92, 0xcf,
	0xf7, 0xa1, 0x71, 0x5e, 0x01, 0x8c, 0x58, 0x34, 0x9b, 0x90, 0x64, 0x46, 0x25, 0x6a, 0x42, 0x45,
	0xd0, 0x44, 0xe5, 0x95, 0xcd, 0x94, 0x5c, 0x44, 0x27, 0x50, 0x0d, 0xb9, 0x4f, 0xe4, 0x66, 0xa0,
	0xac, 0x65, 0xe5, 0x45, 0x82, 0x20, 0xa1, 0x42, 0x64, 0x03, 0x24, 0x17, 0x9d, 0x3f, 0x19, 0x76,
	0x4c, 0x45, 0x1a, 0x4a, 0xf4, 0x39, 0x94, 0xa5, 0xde, 0x47, 0x9b, 0xd9, 0x0f, 0x1e, 0xe7, 0x26,
	0x18, 0x9c, 0x19, 0xab, 0xad, 0x83, 0x84, 0xc7, 0x98, 0x48, 0x13, 0x55, 0x01, 0xaf, 0x65, 0xd5,
	0xe5, 0x21, 0x91, 0x34, 0xf2, 0x57, 0x57, 0x42, 0xc7, 0x55, 0xc0, 0x1b, 0xc0, 0xf9, 0x06, 0x1a,
	0x17, 0x3c, 0x0a, 0x58, 0x34, 0xeb, 0xcc, 0x49, 0x18, 0xd2, 0x68, 0x46, 0xd5, 0x75, 0x0d, 0x98,
	0xd0, 0xfd, 0x6b, 0x52, 0x2c, 0x2b, 0xb1, 0x1f, 0x28, 0xc5, 0x1d, 0x9b, 0xb2, 0xbc, 0xb1, 0x6b,
	0xb8, 0xac, 0xc4, 0x7e, 0xa0, 0x0e, 0x2f, 0xe2, 0x91, 0x4f, 0x75, 0xd4, 0xbb, 0xd8, 0x08, 0x0e,
	0x86, 0xc3, 0x76, 0x2a, 0xe7, 0x34, 0x92, 0xcc, 0x27, 0x92, 0x66, 0x97, 0x08, 0x7d, 0x05, 0x35,
	0x3f, 0xdf, 0x4b, 0x6f, 0xf0, 0x70, 0x9a, 0x9b, 0xcb, 0x8b, 0x37, 0xf6, 0xce, 0x1f, 0xe1, 0x60,
	0x1d, 0xe8, 0xfa, 0x06, 0xbe, 0x76, 0x91, 0xad, 0x7b, 0x17, 0x19, 0x7d, 0x0c, 0x07, 0x3e, 0x4d,
	0x24, 0x9b, 0xea, 0x28, 0x3c, 0x7f, 0x4e, 0x58, 0x94, 0x5d, 0xf7, 0xc6, 0x96, 0xa2, 0xa3, 0x70,
	0xe7, 0x3f, 0x45, 0x68, 0x0c, 0xa8, 0xbc, 0xe3, 0xc9, 0x4d, 0x3f, 0x92, 0x34, 0x99, 0x12, 0x9f,
	0xaa, 0xe1, 0x11, 0x91, 0x45, 0x5e, 0x70, 0xbd, 0x56, 0xb7, 0x3e, 0x8d, 0xf5, 0xcc, 0xae, 0xe2,
	0x42, 0x1a, 0xa3, 0x1e, 0x54, 0x93, 0xa5, 0x27, 0x24, 0x91, 0xe6, 0x94, 0xed, 0xf3, 0x8f, 0x1f,
	0x48, 0xea, 0x3e, 0x75, 0x0b, 0x2f, 0xd5, 0x20, 0x13, 0xb8, 0x92, 0x98, 0x85, 0xe2, 0x91, 0x39,
	0x4f, 0xf1, 0xdd, 0x79, 0x26, 0x39, 0x8f, 0xcc, 0x78, 0x9e, 0x43, 0x95, 0xca, 0x39, 0x4d, 0x22,
	0x2a, 0x9b, 0xff, 0xaa, 0xbc, 0x95, 0xc8, 0xcd, 0x6c, 0xee, 0x13, 0x3e, 0x7b, 0x0f, 0xaf, 0xfd,
	0xd1, 0x13, 0x28, 0xa9, 0x42, 0xe7, 0x63, 0xfa, 0xc3, 0x07, 0x78, 0x5e, 0xb2, 0x29, 0x7b, 0x80,
	0x43, 0xfb, 0x9d, 0xbc, 0x82, 0x4a, 0x96, 0xa7, 0xea, 0x94, 0xeb, 0x95, 0xa4, 0xf9, 0xb4, 0x36,
	0x82, 0xba, 0x1e, 0x31, 0xf1, 0x6f, 0x68, 0x76, 0x76, 0x25, 0x9c, 0x8b, 0xea, 0x23, 0x39, 0x4d,
	0xc8, 0x82, 0x7a, 0x34, 0x49, 0x78, 0x62, 0x8e, 0xa4, 0x84, 0x6d, 0x8d, 0xb9, 0x1a, 0x3a, 0xf9,
	0x35, 0x54, 0x26, 0xff, 0x1f, 0xfb, 0x85, 0x0d, 0x35, 0x96, 0x47, 0xeb, 0xfc, 0xb9, 0x00, 0xcd,
	0xb7, 0x1d, 0x07, 0xfa, 0x29, 0xd4, 0x43, 0x16, 0xdd, 0x78, 0x01, 0x95, 0xd4, 0x97, 0xd4, 0xdc,
	0x8c, 0x2a, 0xde, 0x55, 0x60, 0x37, 0xc3, 0xd4, 0x44, 0x13, 0x31, 0xa5, 0x81, 0xb7, 0xb8, 0x8e,
	0xcd, 0x5e, 0x75, 0x5c, 0xd3, 0xc8, 0xd5, 0x75, 0x2c, 0xd0, 0x2f, 0x01, 0x91, 0x54, 0xf2, 0x88,
	0xce, 0xb8, 0x64, 0x7a, 0x2e, 0x78, 0xd9, 0x83, 0xa2, 0x8a, 0x0f, 0xee, 0x69, 0x86, 0x11, 0x7a,
	0x0e, 0xe5, 0x20, 0x8d, 0x43, 0xba, 0xd4, 0x5d, 0xb6, 0x77, 0x7e, 0xfe, 0x3d, 0xca, 0xd7, 0xea,
	0x6a, 0x4f, 0x9c, 0x31, 0x38, 0x1f, 0x41, 0xd9, 0x20, 0xc8, 0x86, 0xca, 0x8b, 0xc1, 0x6f, 0x07,
	0xc3, 0x97, 0x83, 0xc6, 0x7b, 0xa8, 0x0a, 0xa5, 0x67, 0xed, 0xcb, 0x5e, 0xc3, 0x52, 0xab, 0xde,
	0x8b, 0xcb, 0xcb, 0x46, 0xc1, 0xf9, 0x4b, 0x19, 0x1e, 0x3d, 0x54, 0x4d, 0xf4, 0x0a, 0xf6, 0xd4,
	0x6e, 0x0b, 0x12, 0xea, 0xf6, 0x4c, 0x45, 0x76, 0x79, 0x3f, 0x7f, 0xc7, 0x76, 0x68, 0x4d, 0x8c,
	0xf7, 0x58, 0x3b, 0xe3, 0xba, 0xdc, 0x16, 0x11, 0x87, 0x23, 0x16, 0xdd, 0x92, 0x90, 0x05, 0x9e,
	0xa9, 0x8e, 0xf9, 0x2e, 0xe4, 0x97, 0xe9, 0xab, 0x77, 0xdd, 0xa4, 0x6f, 0x48, 0x46, 0x9a, 0x43,
	0x8f, 0x7f, 0x81, 0x0f, 0xd9, 0x9b, 0xa0, 0xea, 0x0a, 0x7f, 0x4e, 0xa2, 0x88, 0x86, 0xba, 0x04,
	0x75, 0x9c, 0x8b, 0xe8, 0x67, 0xb0, 0xb7, 0x60, 0x42, 0xd0, 0xc0, 0xbb, 0xa6, 0xc4, 0xe7, 0x91,
	0xd0, 0xaf, 0xa0, 0x3a, 0xae, 0x1b, 0xf4, 0xc2, 0x80, 0xaa, 0x35, 0x75, 0x4b, 0xa8, 0xb7, 0x14,
	0x93, 0x2b, 0x5d, 0x25, 0x0b, 0xdb, 0x0a, 0xfb, 0x9d, 0x81, 0x94, 0x89, 0x9e, 0x43, 0xa1, 0x17,
	0xd2, 0x5b, 0x1a, 0xea, 0xf7, 0x9b, 0x85, 0x6d, 0x83, 0x5d, 0x2a, 0x08, 0xfd, 0x18, 0xec, 0x88,
	0x33, 0x41, 0x33, 0x8b, 0xb2, 0xb6, 0x00, 0x0d, 0x69, 0x83, 0x93, 0xbf, 0x5a, 0x50, 0x7f, 0xed,
	0xe4, 0x54, 0x97, 0x1b, 0x63, 0x4b, 0x87, 0x65, 0x04, 0xf4, 0x3e, 0x94, 0x24, 0x5d, 0xc4, 0xa6,
	0xed, 0x2e, 0x0a, 0x4d, 0x0b, 0x6b, 0x59, 0x59, 0xab, 0xdf, 0x73, 0x9d, 0xa5, 0x85, 0x8d, 0x80,
	0x3e, 0x84, 0xfd, 0x98, 0xdf, 0xd1, 0xc4, 0x4b, 0x68, 0x90, 0xfa, 0xfa, 0x9b, 0x55, 0xd2, 0x6c,
	0x7b, 0x1a, 0xc6, 0x39, 0xaa, 0x7a, 0x3a, 0x48, 0xe5, 0xca, 0xf3, 0x57, 0x7e, 0x48, 0x75, 0x02,
	0x75, 0x5c, 0x53, 0x48, 0x47, 0x01, 0x27, 0xff, 0xb4, 0xe0, 0xf0, 0x81, 0x23, 0x47, 0x3f, 0x87,
	0xfd, 0x64, 0xe9, 0xe5, 0x15, 0x8d, 0xee, 0xb2, 0x6f, 0x49, 0x1d, 0xd7, 0x93, 0x65, 0x66, 0x3f,
	0xb8, 0x63, 0x01, 0x3a, 0x83, 0xc6, 0x96, 0x9d, 0x9f, 0xac, 0x62, 0x99, 0x5d, 0x9c, 0xbd, 0xb5,
	0x61, 0x47, 0xa1, 0xf7, 0x18, 0xa7, 0x09, 0x99, 0x65, 0x75, 0xdb, 0x30, 0xf6, 0x12, 0x32, 0x43,
	0x9f, 0xc2, 0x23, 0xb9, 0xf4, 0xe8, 0xd2, 0xa7, 0x42, 0xb0, 0x5b, 0xea, 0x25, 0x54, 0x26, 0x8c,
	0x8a, 0x2c, 0x3d, 0x24, 0x97, 0x6e, 0xae, 0xc2, 0x46, 0xa3, 0xaa, 0x94, 0xd3, 0x2e, 0x98, 0xf0,
	0xb3, 0x24, 0xed, 0x0c, 0xbb, 0x62, 0xc2, 0x7f, 0x5e, 0xaa, 0x56, 0x1a, 0x55, 0xa7, 0x03, 0xf6,
	0xe5, 0x65, 0x7b, 0xc4, 0x85, 0x7e, 0x45, 0xab, 0x47, 0x44, 0x48, 0xa4, 0xce, 0xcb, 0xc2, 0x6a,
	0xa9, 0x91, 0xec, 0xeb, 0xaf, 0x10, 0x63, 0x43, 0x42, 0x99, 0x9d, 0xbd, 0x5a, 0x3a, 0x5f, 0xc0,
	0xae, 0xdb, 0x71, 0x7b, 0x6b, 0x96, 0x5d, 0xb0, 0x96, 0x19, 0x87, 0xb5, 0x54, 0xd2, 0x2a, 0xf3,
	0xb7, 0x56, 0x4a, 0xfa, 0x2e, 0xf3, 0xb5, 0xbe, 0x73, 0x4e, 0xa0, 0xd9, 0x8f, 0x98, 0x1a, 0x10,
	0x14, 0xd3, 0x05, 0x97, 0x74, 0x2c, 0xe6, 0xf9, 0xcb, 0x94, 0xc0, 0xe3, 0x07, 0x74, 0xd9, 0xf7,
	0x11, 0x41, 0x29, 0xe6, 0x89, 0xcc, 0x2a, 0xa0, 0xd7, 0xdb, 0x2f, 0x92, 0xc2, 0x6b, 0x2f, 0x12,
	0xf4, 0x3e, 0x94, 0x85, 0x14, 0x64, 0x9a, 0x7f, 0xcd, 0x33, 0xe9, 0x17, 0x7f, 0xb3, 0x00, 0x36,
	0x4f, 0x39, 0x74, 0x0c, 0x87, 0x17, 0xc3, 0xe1, 0xc4, 0xc3, 0x6e, 0x7b, 0x3c, 0x1c, 0x78, 0x9b,
	0xa1, 0x52, 0x87, 0x5a, 0x6f, 0x88, 0x9f, 0x0e, 0x27, 0x13, 0x77, 0xd0, 0xb0, 0xd0, 0x3e, 0xd8,
	0xa3, 0xe1, 0x4b, 0x17, 0x7b, 0x9d, 0x3f, 0x74, 0x2e, 0xdd, 0x46, 0x41, 0x4d, 0xa0, 0xce, 0xf0,
	0xea, 0xaa, 0x3d, 0xe8, 0x36, 0x8a, 0xe8, 0x10, 0xf6, 0xc7, 0xc3, 0xde, 0xe4, 0x65, 0x1b, 0xbb,
	0xde, 0x8b, 0x51, 0xb7, 0x3d, 0x71, 0x1b, 0x25, 0x74, 0x00, 0xf5, 0xce, 0x70, 0xd0, 0xeb, 0x3f,
	0xcd, 0xa1, 0x1d, 0xc5, 0xf2, 0x62, 0x34, 0xe9, 0x5f, 0xb9, 0x5e, 0xaf, 0xdb, 0xc7, 0x8d, 0xb2,
	0xb2, 0xc1, 0xee, 0xc8, 0x6d, 0x4f, 0x5c, 0x6c, 0xa0, 0xca, 0xc5, 0xf1, 0x37, 0x47, 0xe6, 0xdf,
	0x62, 0xcb, 0xe7, 0x8b, 0xad, 0x7f, 0x8c, 0xd7, 0x65, 0xfd, 0x5f, 0xf1, 0xb3, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xa4, 0xf9, 0xf5, 0xbd, 0x4d, 0x0e, 0x00, 0x00,
}
